name: Static Analysis (Linting)

# This workflow is triggered on pushes to trunk, and any PRs.
on:
    push:
        branches: [trunk]
    pull_request:

jobs:
    check:
        name: All

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

            - name: Setup
              uses: WordPress/wporg-repo-tools/.github/actions/setup@trunk
              with:
                packageManager: "npm"
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Lint
              uses: WordPress/wporg-repo-tools/.github/actions/lint@trunk
