name: Unit Tests

# Run on any changes in public_html
on:
    pull_request:
        paths:
            - public_html/**
    push:
        branches: [trunk]
        paths:
            - public_html/**
    # Enable manually running action if necessary.
    workflow_dispatch:

jobs:
    unit-php:
        name: PHP

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

            - name: Setup
              uses: WordPress/wporg-repo-tools/.github/actions/setup@trunk
              with:
                packageManager: "npm"
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install WordPress
              run: |
                  chmod -R 767 ./ # TODO: Possibly integrate in wp-env
                  npm run wp-env start --update
                  npm run wp-env run tests-cli wp core version
                  npm run wp-env run tests-cli wp plugin list

            - name: Running multisite unit tests
              run: npm run test:php
              if: ${{ success() || failure() }}

    unit-js:
        name: JS

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

            - name: Setup
              uses: WordPress/wporg-repo-tools/.github/actions/setup@trunk
              with:
                packageManager: "npm"
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Run unit tests on theme data store
              run: npm run test:unit --workspace=wporg-pattern-directory-theme 

            - name: Run unit tests on the pattern creator
              run: npm run test:unit --workspace=wporg-pattern-creator 
