name: Unit Tests

# Run on any changes in public_html
on:
    pull_request:
        paths:
            - public_html/**
    push:
        branches: [trunk]
        paths:
            - public_html/**
    # Enable manually running action if necessary.
    workflow_dispatch:

jobs:
    unit-php:
        name: PHP

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

            - name: Set PHP version
              uses: shivammathur/setup-php@e04e1d97f0c0481c6e1ba40f8a538454fe5d7709 # v2.21.2
              with:
                  php-version: 7.4
                  coverage: none
                  tools: composer:v2

            - name: Install PHP dependencies
              run: |
                  composer install

            - name: Install NodeJS
              uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
              with:
                  node-version-file: '.nvmrc'
                  cache: npm

            - name: Install JS dependencies
              run: |
                  npm install

            - name: Build
              run: npm run build --workspaces

            - name: Install WordPress
              run: |
                  chmod -R 767 ./ # TODO: Possibly integrate in wp-env
                  npm run wp-env start --update
                  npm run wp-env run tests-cli wp core version
                  npm run wp-env run tests-cli wp plugin list

            - name: Running multisite unit tests
              run: npm run test:php
              if: ${{ success() || failure() }}

    unit-js:
        name: JS

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

            - name: Install NodeJS
              uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
              with:
                  node-version-file: '.nvmrc'
                  cache: npm

            - name: Set PHP version
              uses: shivammathur/setup-php@e04e1d97f0c0481c6e1ba40f8a538454fe5d7709 # v2.21.2
              with:
                  php-version: 7.4
                  coverage: none
                  tools: composer:v2

            - name: Install PHP dependencies
              run: |
                  composer install

            - name: Install JS dependencies
              run: |
                  npm

            - name: Build
              run: npm run build --workspaces

            - name: Run unit tests on theme data store
              run: npm run test:unit --workspace=wporg-pattern-directory-theme 

            - name: Run unit tests on the pattern creator
              run: npm run test:unit --workspace=wporg-pattern-creator 
